# Q1. What are the benefits of the built-in array package, if any?

Ans :
    The following are some advantages of arrays:

Arrays are similar to lists. The main difference is that arrays can store only one type of elements; whereas, lists can store different types of elements. 

When dealing with a huge number of elements, arrays use less memory than lists and they offer faster execution than lists.

The size of the array is not fixed in Python. Hence, we need not specify how many elements we are going to store into an array in the beginning.

Arrays can grow or shrink in memory dynamically (during runtime).

Arrays are useful to handle a collection of elements like a group of numbers or characters.

Methods that are useful to process the elements of any array are available in 'array' module.

# Q2. What are some of the array package&#39;s limitations?

The number of elements to be stored in an array should be known in advance. An array is a static structure (which means the array is of fixed size). Once declared the size of the array cannot be modified. The memory which is allocated to it cannot be increased or decreased.

Insertion and deletion are quite difficult in an array as the elements are stored in consecutive memory locations and the shifting operation is costly.

Allocating more memory than the requirement leads to wastage of memory space and less allocation of memory also leads to a problem

# Q3. Describe the main differences between the array and numpy packages.

he array package doesn't provide any help with numerical calculation with the items insdie it in number form while NumPy give you a wide variety of numerical operations.

An array is a single dimensional entity which hold the numerical data, while numpy can have more than 1 dimension.

In case of array, item can be accessed by its index position and it is easy task while in numpy item is accessed by its column and row index, which makes it slightly time taking. Same goes with appending operation.

In case of array we do not form a tabular structure, while in numpy it forms a tabular structure

# Q4. Explain the distinctions between the empty, ones, and zeros functions.

Ans: numpy.empty(shape, dtype = float, order = ‘C’) : Return a new array of given shape and type, with random values.

In [6]:
#Example 
import numpy as np
a=np.empty(2,dtype=int)
print(a)
print("************************************")
b=np.empty([2,2],dtype=float)
print(b)
print("**************************************")
c=np.empty([3,3],dtype=int)
print(c)

[-1370313136         667]
************************************
[[1.41682146e-311 1.41681616e-311]
 [1.41681616e-311 1.41681616e-311]]
**************************************
[[          0           0  1440309328]
 [      32764           1           0]
 [         -1          -1 -1919942656]]


In [8]:
a=np.ones([2,2])
print(a)

[[1. 1.]
 [1. 1.]]


In [10]:
b=np.zeros([1,2])
print(b)

[[0. 0.]]


# Q5. In the fromfunction function, which is used to construct new arrays, what is the role of the callable argument?

Ans:numpy.fromfunction(function, shape, *, dtype=<class 'float'>, like=None, **kwargs)[source]
Construct an array by executing a function over each coordinate.

The resulting array therefore has a value fn(x, y, z) at coordinate (x, y, z).

Parameters:
functioncallable
The function is called with N parameters, where N is the rank of shape. Each parameter represents the coordinates of the array varying along a specific axis. For example, if shape were (2, 2), then the parameters would be array([[0, 0], [1, 1]]) and array([[0, 1], [0, 1]])

shape(N,) tuple of ints
Shape of the output array, which also determines the shape of the coordinate arrays passed to function.

dtypedata-type, optional
Data-type of the coordinate arrays passed to function. By default, dtype is float.

likearray_like, optional
Reference object to allow the creation of arrays which are not NumPy arrays. If an array-like passed in as like supports the __array_function__ protocol, the result will be defined by it. In this case, it ensures the creation of an array object compatible with that passed in via this argument.
Returns:
fromfunctionany
The result of the call to function is passed back directly. Therefore the shape of fromfunction is completely determined by function. If function returns a scalar value, the shape of fromfunction would not match the shape parameter.

Its function is to execute the function over each coordinate and the resulting array. The function is called with N parameters, where N is the rank of shape. Each parameter represents the coordinates of the array varying along a specific axis.

In [15]:
#Example :
a=np.fromfunction(lambda i,j:j,[2,2],dtype=float)
print(a)

b=np.fromfunction(lambda i,j:i==j,[3,3],dtype=int)
print(b)

[[0. 1.]
 [0. 1.]]
[[ True False False]
 [False  True False]
 [False False  True]]


# Q6. What happens when a numpy array is combined with a single-value operand (a scalar, such as an int or a floating-point value) through addition, as in the expression A + n?

when a numpy array is combined with a single-value operand (a scalar, such as an int or a floating-point value) through addition,that number is added element wise to each element in array

In [25]:
import numpy as np
A=np.array([1,2,3,4,5,6,7,8]).reshape(4,2)
print(A)
n=12
print(n)
print(A+n)

[[1 2]
 [3 4]
 [5 6]
 [7 8]]
12.0
[[13. 14.]
 [15. 16.]
 [17. 18.]
 [19. 20.]]


# Q7. Can array-to-scalar operations use combined operation-assign operators (such as += or *=)? What is the outcome?

Ans:It will carry out provided operation on all elements of array.

# Q8. Does a numpy array contain fixed-length strings? What happens if you allocate a longer string to one of these arrays?

 Yes, it is possible that we can include a string of fixed length in numpy array. The dtype of any numpy array containing string values is the maximum length of any string present in the array.Once set, it will only be able to store new string having length not more than the maximum length at the time of the creation. If we try to reassign some another string value having length greater than the maximum length of the existing elements, it simply discards all the values beyond the maximum length accept upto those values which are under the limit.

In [30]:
import numpy as np
country=np.array(['India','US','UK',' ','China'])
print(country)
#Try to reassign value NewZealand to ' '
country[country==' ']='NewZealand'
print(country)

['India' 'US' 'UK' ' ' 'China']
['India' 'US' 'UK' 'NewZe' 'China']


# Q9. What happens when you combine two numpy arrays using an operation like addition (+) or multiplication (*)? What are the conditions for combining two numpy arrays?

Ans: It will simply add or multiply element to element at same position.

In [34]:
#Example 
import numpy as np
A=np.array([[1,2,3],[4,5,6],[7,8,9]])
B=np.array([[9,8,7],[6,5,4],[3,2,1]])
print(A+B)
print("*******************************")
print(A*B)

[[10 10 10]
 [10 10 10]
 [10 10 10]]
*******************************
[[ 9 16 21]
 [24 25 24]
 [21 16  9]]


# Q10. What is the best way to use a Boolean array to mask another array?

Ans:Using Masking of arrays we can easily handle the missing, invalid, or unwanted entries in our array or dataset/dataframe. Masking is essential works with the list of Boolean values i.e, True or False which when applied to an original array to return the element of interest, here True refers to the value that satisfies the given condition whereas False refers to values that fail to satisfy the condition.

We can mask the array using another by using the following functions:-

numpy.ma.masked_where(condition, arr)

In [47]:
#Example :
import numpy as np 
def masked(arr1,arr2):
    masked_arr=np.ma.masked_where(arr2%7,arr1)
    return masked_arr
A=np.array([1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21])
B=np.array([1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21])
mask=masked(B,A)
print("Masked array is ",np.ma.compressed(mask))

Masked array is  [ 7 14 21]


# Q11. What are three different ways to get the standard deviation of a wide collection of data using both standard Python and its packages? Sort the three of them by how quickly they execute.

In [50]:
A=np.array([1,2,34,677,90,78,76,45,23,11,10])

In [51]:
#one way using numpy 
import numpy as np
print("Using numpy package",np.std(A))

Using numpy package 186.49144176406506


In [53]:
#Second way using statistics module 
import statistics
print("Using statistics module",statistics.stdev(A))

Using statistics module 195.5914108543624


In [57]:
#Using math 
import math
import sys
def sd_calc(data):
    n = len(data)
    if n <= 1:
        return 0.0
    mean, sd = avg_calc(data), 0.0
    # calculate stan. dev.
    for el in data:
        sd += (float(el) - mean)**2
    sd = math.sqrt(sd / float(n-1))
    return sd

def avg_calc(ls):
    n, mean = len(ls), 0.0
    if n <= 1:
        return ls[0]
    # calculate average
    for el in ls:
        mean = mean + float(el)
    mean = mean / float(n)
    return mean
data=np.array([1,2,34,677,90,78,76,45,23,11,10])
print("Sample Data: ",data)
print("Standard Deviation : ",sd_calc(data))

Sample Data:  [  1   2  34 677  90  78  76  45  23  11  10]
Standard Deviation :  195.59387423015997


# 12. What is the dimensionality of a Boolean mask-generated array?

 It will have same dimensionality as input array.